### ISSUE TITLE
Computation of the accuracy scores when there are compilation and runtime errors

### ISSUE THREAD

**Issue by loubnabnl** [hendrycks/apps#11]
Hi thank you for this great dataset! I have some questions about how you compute the accuracy scores in this https://github.com/hendrycks/apps/blob/c55cce35806c14423b41decf7241615261cf9de0/eval/test_one_solution.py#L22-L42 I was curious why you use `-2` and `-1` for compilation and runtime errors and include them in the average computation of the accuracy which could lead to a negative score. It seems more natural to give a `False` label to a code with syntax/runtime error similarily to a code that just doesn’t pass the unit tests.

Also the expression `all_correct.append(np.all(results[index]))` will consider -2 and -1 as `True` since `np.all` evaluates non zero numbers to `True`, which could  give a false accuracy. 

Below is an example:
```python
print_results({0: [[-2]], 1: [[-2]], 2: [[-2]], 3: [[-2]]}, args)
```

```
number of compile errors = 1 avg = 0.25
number of runtime errors = 1 avg = 0.25
number of test cases run = 4
Test Case Average (average accuracy over problems) = -2.0
Strict Accuracy (all test cases passed / total problems) = 1.0
```

Another thing regarding the expressions:
```python
 compile_errors = len(tmp_results[tmp_results==-2])
 runtiome_errors = len(tmp_results[tmp_results==-1])
```
 if I'm not mistaken this doesn't  work (at least on Python 3.9), another implementation could be 
```python
 compile_errors = len([e for e in tmp_results if -2 in e])
 runtiome_errors = len([e for e in tmp_results if -1 in e])
```

**Comment by xksteven** [comment]
Thanks for catching the bug. Think we forgot to add a "> 0" on line 29. 
I'll push the big fix soon. 

As for your other question. I thought it was a good metric that ultimately wasn't used to be able to measure how often does the model even produce code that runs compared to gibberish. So compile errors were worse in my opinion than runtime errors. It can also be seen as measuring grammar vs semantic errors in a loose way.

**Comment by loubnabnl** [comment]
Thank you for your reply and for the fix!  Regarding the comment above `tmp_results` is defined as a list in the function, maybe we could add `res.extend(np.array(results[index]))` here https://github.com/hendrycks/apps/blob/d5c8e99aff17560ae1a4ccc89f27d0371f7a6e84/eval/test_one_solution.py#L27 
and `tmp_results = np.array(res)` here https://github.com/hendrycks/apps/blob/d5c8e99aff17560ae1a4ccc89f27d0371f7a6e84/eval/test_one_solution.py#L30

**Comment by xksteven** [comment]
I'll make the changes you suggested but also feel free to make a pull requests too.  Thanks for looking through it and adding it to hugging face!
