### ISSUE TITLE
Nan test case average

### ISSUE THREAD

**Issue by sindhura97** [hendrycks/apps#14]
Hello,
I am trying to evaluate my model's generated codes using scripts in eval. However, for a particular problem, results[index] turns out to be an empty array as a result of which calculating mean in print_results() gives nan. How should I handle this case?

**Comment by xksteven** [comment]
Curious what your results array looks like or at least the relevant portion.

Here's the example results that the code gives us: https://github.com/hendrycks/apps/blob/main/eval/test_one_solution.py#L19

**Comment by sindhura97** [comment]
This is my results array: {4530: [[False, False, True]], 4531: [[False, True, False]], 4532: [[False, True, False]], 4533: [[-2]], 4534: [[]]}

**Comment by xksteven** [comment]
Since I'm not sure how that was generated the easiest thing would be to post process your results and just convert any of the `[[]]` to `[[-2]]`.

**Comment by xksteven** [comment]
Any updates on this issue? Otherwise I'll close it soon.

**Comment by sindhura97** [comment]
I just did what you suggested, no more updates.
