### ISSUE TITLE
Running instructions

### ISSUE THREAD

**Issue by PulkitMadan** [hendrycks/apps#17]
Reference: https://github.com/hendrycks/apps#how-to-use

Files train/README and eval/README are not present in the repository. 
Would really appreciate if the instructions are added for training and evaluation of the models.

**Comment by xksteven** [comment]
I'll check what happened to them. I remember they used to be there but maybe I'm mistaken. Will double check soon. Thanks for raising the issue.

**Comment by xksteven** [comment]
I do not believe we plan to release the filtered dataset as the hosting costs are too much for the size of dataset.

**Comment by xksteven** [comment]
The links in the README were broken but the actual README instructions for train and eval were present in their respective folders.  I've updated the links and will now close the issue.

Thanks for reporting it!
