### ISSUE TITLE
Categorization of Problem Difficulty

### ISSUE THREAD

**Issue by eelxpeng** [hendrycks/apps#2]
Hi, thanks for providing the benchmark dataset. From the paper, problems are categorized into Introductory, Interview, Competition, etc. Could you provide the problem ids corresponding to the difficulty level? It would help a lot.

**Comment by hendrycks** [comment]
The metadata.json in each problem folder indicates the difficulty.

**Comment by hendrycks** [comment]
We are in the process of rescraping codeforces to investigate this issue.

**Comment by hendrycks** [comment]
Div I/IOI is competition-level, Div II is interview, and Div III is introductory.
