### ISSUE TITLE
Problems With APPS

### ISSUE THREAD

**Issue by MT010104** [hendrycks/apps#20]
Hi. When using the dataset to evaluate the fine-tuned model, I found that the test set has some problems without solution.json. Could you provide the complete set?
<img width="418" alt="image" src="https://user-images.githubusercontent.com/65756145/196309219-6be80f17-fda0-4599-b0ff-97ffc747ac9d.png">

**Comment by MT010104** [comment]
However, for the generated code, we need to calculate the BLEU. So we need the canonical code as a reference. If part of the problems do not have "solutions.json", we will consider discarding this part of the data.

**Comment by xksteven** [comment]
I'll double check for you.

**Comment by xksteven** [comment]
Our final requirements for passing a solution was quite strict.  I couldn't find any of the solutions that passed all the criterion so we don't have any.  If we rescrape those at a later time I'll be sure to update this ticket.  Unsure when that'll happen though.
