### ISSUE TITLE
Why don't add sorted(problems) to pin problems sorting?

### ISSUE THREAD

**Issue by guoday** [hendrycks/apps#3]
Hi, thanks for your hard works.

Whether should we add a line of code `problems = sorted(problems)` [here](https://github.com/hendrycks/apps/blob/473a49713a708191b51175691553d88291f8e907/eval/test_one_solution.py#L48) to pin some ordering? Just like:
https://github.com/hendrycks/apps/blob/473a49713a708191b51175691553d88291f8e907/eval/generate_gpt_codes.py#L113

If I have any mistake, please point out.

Thanks

**Comment by xksteven** [comment]
Thanks for the suggestion!  Feel free to make a pull request next time.  
I did the fix and pushed it.
Let me know if you encounter any other issues or have other suggestions :)
