### ISSUE TITLE
Do I need to still reindent if I'm using the APPS dataset hosted on HuggingFace?

### ISSUE THREAD

**Issue by Laknath1996** [hendrycks/apps#31]
I'm browsing through the APPSBaseDataset code and noticed that the code is reindented to match the format of the Github dataset. If I'm using the APPS dataset from HuggingFace, do I still need to do the reindentation before fine-tuning a model on it?

**Comment by xksteven** [comment]
You don't need to. We used to to save on tokens. We just noticed that spaces were taking up a lot of the tokens for GPT tokenizer and thus some answers or outputs were being cutoff. We worked to limit that from happening with the reindent function we used. Other tokenizers will likely not have this issue and so you should be okay not to use it.
