### ISSUE TITLE
Missing apps-train-files json file?

### ISSUE THREAD

**Issue by ywen666** [hendrycks/apps#4]
Hi,

Thank you for releasing this amazing codebase! I found that the appsdata need to take apps-train-files json file as an input but I couldn't find anything in the provided apps dataset. I wonder if I am missing somewhere. 

Thanks!

**Comment by xksteven** [comment]
Could you please provide more details on what you're trying to do?

I couldn't understand from your description.

**Comment by ywen666** [comment]
I couldn't find the file this line requires in the dataset (https://github.com/hendrycks/apps/blob/main/train/tune_apps_gpt.py#L159). But I think it is just a json file with list of training folders.

**Comment by xksteven** [comment]
I'll update you later tonight. I need to redownload the apps dataset as I thought we included it in there.
Otherwise I'll create a new one and upload it to the git repo. After that I'll update the README and this issue.

**Comment by ywen666** [comment]
Not a big issue because the json file can be inferred from the APPSBaseDataset.py file. Btw, I wonder how many gpus need to fine-tune the gpt-neo on apps. I saw the batch size per replica is only 2.

**Comment by xksteven** [comment]
I added the instructions here: https://github.com/hendrycks/apps/blob/main/train/README.md
and the script here: https://github.com/hendrycks/apps/blob/main/train/apps_create_split.py

As for how many GPUs I believe it is listed in the paper.  I can't remember the numbers off hand.
