### ISSUE TITLE
Request for pretrained models

### ISSUE THREAD

**Issue by changransn** [hendrycks/apps#8]
Hey there! 
Congrats and thanks for the amazing work! The APPS dataset would benefit the community greatly.
I really appreciate that you released the GPT2-1.5B finetuned model, but just curious would it possible to release the pretrained GPT2-1.5B model as well?

Thank you in advance and happy new year!

**Comment by xksteven** [comment]
We suggest using the [Neo](https://github.com/EleutherAI/gpt-neo) model as a good replacement.

**Comment by changransn** [comment]
Gotcha, thanks for the quick response!
